

function card(name, description, image) {
    this.name = name;
    this.description = description;
    this.image = image;
  }
  
  var deck = [
    //major arcana upright
    new card('The Fool', 'You are embarking on a new journey, one where you will be filled with optimism and freedom from the usual constraints in life. You are called to tap into the risk-taking part of your own character.', 'fool'),
    new card('The Magician', 'It is time to tap into your full potential without hesitation. It might be a your new job, new business venture, a new love or something else. The time to take action is now and any signs of holding back means missing the opportunity of becoming the best version of yourself.', 'magician'),
    new card('The High Priestess', 'There is searching within yourself to be done for the answers that you seek. The answers to the questions you have are within, not without.', 'high-priestess'),
    new card('The Empress', 'The Empress shows us how deeply we are embedded to our femininity. Femininity could be associated with fertility, expression, creativity and nurturing among many other aspects. It therefore calls you to connect with beauty and bring happiness to your life. Understand yourself and get in touch with your sensuality so that you can attract life circumstances to bring happiness and joy.', 'empress'),
    new card('The Emperor', 'Claim your authority as leader and influencer and don’t let others put you down. Create calm out of chaos by breaking down any problem into its parts and then mapping out the actions you need to take to resolve it. Be systematic, strategic and highly organised in your approach, and stick to your plan until the end.', 'emperor'),
    new card('The Hierophant', 'Follow the key principles and rules that you know will lead to a successful result. If you are interested in mastering a field, you are encouraged to learn the fundamental principles from a trusted source.', 'hierophant'),
    new card('The Lovers', 'Communicating openly and honestly with those you care about will create a harmonious and fulfilling relationship built on trust and respect. Alternatively, this card signals that it is time to go into the big wide world and make choices for yourself, staying true to who you are and being authentic and genuine in all your endeavours.', 'lovers'),
    new card('The Chariot', 'You must maintain focus, confidence, and determination through a process that will be full of winding turns and detours. Your boldness will ensure that you achieve all that you should in this goal.', 'chariot'),
    new card('Strength', 'In whatever situation you are in, your resilience will greatly aid you and your fearlessness will show that you have no issues speaking your mind.', 'strength'),
    new card('The Hermit','You are currently contemplating that you need to be alone. Never be afraid to take this chance to reflect, as it could help you clear your mind of all the clutter that comes with everyday life.', 'hermit'),
    new card('The Wheel of Fortune', 'Greater forces that are outside of human control are at work here. The same forces that govern the changing of the seasons, or the rising and setting of the sun is also the master of luck and the fate of individuals. Where it lands is as random as chance - you may find yourself at either the top or bottom, but remember that no matter what the outcome it may not last for very long, for the wheel always turns.', 'wheel'),
    new card('Justice', 'The decisions that you make now have long-term effects in all things, both for yourself and others. There will always come a time where you will be judged. If you have been wronged, this card may bring you relief. On the other hand, if your actions caused pain to others, this card serves as a warning. Her appearance represents a chance for you to change your actions now for a better future.', 'justice'),
    new card('Hanged Man', 'The hanged man understands that his position is a sacrifice that he needed to make in order to progress forward - whether as repentance for past wrongdoings, or a calculated step backward to recalculate his path onward. This time he spends here will not be wasted, he does this as part of his progression forward. Alternatively, The Hanged Man card reflects a particular need to suspend certain action. As a result, this might indicate a certain period of indecision. This means that certain actions or decisions which need to be properly implemented are likely to be postponed even if there is an urgency to act at this particular moment.', 'hanged-man'),
    new card('Death', 'The Death card signals that you are currently ending a major phase in your life (or about to), and a new one is going to start. The past needs to be placed behind you, so you can focus your energy on what is ahead of you. Death can also mean that you need to let go of any unhealthy attachments that you have in your life.', 'death'),
    new card('Temperance', 'Temperance indicates a time to evaluate and re-examine the priorities you have chosen. This will help you create a balance between your outer and inner self. At the end of it all, you will find greater purpose and meaning in your actions.', 'temperance'),
    new card('The Devil', 'You may be at the effect of negative habits, dependencies, behaviours, thought patterns, relationships, and addictions. You have found yourself trapped between the short-term pleasure you receive and the longer-term pain you experience. To break free of these negative patterns, you need to acknowledge the hold they have over you and the impact they are having on your life and take action to free yourself. It is unlikely that this will be remedied overnight, so a tremendous amount of willpower and strength FROM YOU is required.', 'devil'),
    new card('The Tower', 'The Tower represents change in the most radical and momentous sense. The kind of event that the Tower card marks does not have to be something terrible, like a disaster or a great loss.  Change itself is a normal part of life that one has to embrace. But it can sometimes strike fear, for it means that we must abandon the truths that we have known prior to this event. The old ways are no longer useful, and you must find another set of beliefs, values and processes to take their place. Be positive, it is time for you to replace the old foundations of the past with something that is more genuine and will serve you better in what is to come.', 'tower'),
    new card('The Star', 'The Star brings hope, renewed power, and strength to carry on with life. It shows how abundantly blessed you are by the universe as evidenced by the various things around you. It may not be directly evident at the moment, for this card follows the trauma of the Tower card. Remember that you hold within you all that you need for your fulfillment - the only thing that you need is courage. For this, you have all reasons to rejoice. To see this card is a message to have faith, for the universe will bless you and bring forth all that you need.', 'star'),
    new card('The Moon', 'On one hand, the Moon card can symbolize your imagination is taking the best of you. In the dark of the night, you are taking a path that you are unsure of, for there could be danger lurking in its depths. You are the crawfish embarking on the path in the card. The moonlight can bring you clarity and understanding and you should allow your intuition to guide you through this darkness. You need to be aware of the situations that are causing fear and anxiety in your mind, whether it is now or in the future. It alerts you not to allow inner disturbances and self-deception to take the best of you. These deep memories and fears must be let go, and the negative energies must be released and turned into something constructive. Another reading of the Moon card is the existence of illusion. Some hidden truth must be discovered, for what you are seeing now may just be a trick of the light', 'moon'),
    new card('The Sun', 'The card shows that you have a significant sense of deserved confidence right now. Life is currently particularly good, and the sun is shining your way as you reach the goals that you set. The Sun is one of the cards in the tarot which provide nothing but good feelings and fulfillment.', 'sun'),
    new card('Judgment', 'The traditional Judgement meaning focuses on the moment when we reflect and evaluate ourselves and our actions. It is through self-reflection that we can have a clearer and objective understanding about where we are now, and what we need to do in order to grow as humans. The Judgement card reminds us that we all will be faced with choices that will have an astounding effect for your entire life. The card brings to mind moments where actions you have taken have changed the course of your path for good. There may have been a moment where there is no looking back. The consequences of those actions eventually will catch up to you, and this card seems to indicate that this is the time.', 'judgment'),
    new card('The World', 'The meaning of the World card is fulfillment, achievement, and completion. This shows that all the efforts that you have been putting in place are starting to pay off. It reflects that you have completed a major milestone in your life and you have built the resilience to withstand challenges. The World may indicate completion of a long-term project, study or any other major event in your life. It may also mean the birth of a child, marriage, graduation or any other thing that you have accomplished.', 'world'),
   
    //major arcana reversed
    new card('The Fool Reversed', 'Do not disregard the repercussions of your actions. You are living in the moment and not planning for the future. The reversed Fool meaning serves as caution that you should be more aware so as not to be taken advantage of', 'fool-reversed'),
    new card('The Magician Reversed', 'The reversed Magician is a master of illusion. The magic that he performs is one of deception and trickery. You may be lured in by the showmanship of his arts, but behind that there may be an intention to manipulate for selfish gain', 'magician-reversed'),
    new card('The High Priestess Reversed', 'Something has been telling you to follow your gut, but you may be ignoring the call. There is a lot of confusion around you, and your actions may feel contrary to what you know is right. You must never be afraid to ask questions of yourself that may illuminate a new path forward for you, one that is more authentic to your inner self and your individual values.', 'priestess-reversed'),
    new card('The Empress Reversed', 'you have lost too much of your own willpower and strength because you have started placing too much effort and concern to other people’s affairs and opinions. You might be neglecting your own needs, or even smothering the ones you love with your well-intentioned actions', 'empress-reversed'),
    new card('The Emperor Reversed', 'Assess your relationship with power, control, authority, responsibility and discipline. Are you expressing too much or too little of these elements in your life right now? Are they working for you or against you?. Healing from father-child relationship', 'emperor-reversed'),
    new card('The Hierophant Reversed', 'You are being guided to follow your own path and adopt your own belief systems rather than blindly following others. Challenge the status quo. See alternative ways of viewing the world and test the very ideas and concepts you were taught were the truth.', 'hierophant-reversed'),
    new card('The Lovers Reversed', 'You may be feeling out of sync with those around you, particularly your loved ones. You may find your relationships are strained and communication is challenging. Does it seem as if you are just not on the same page and no longer share the same values? If so, come back to the reason you have this person in your life. If you love them unconditionally, know this moment shall pass and the best you can do is bring love and compassion to the situation. In other cases, you may realise that you have simply grown apart and it’s time to move on. If your relationship continues to be peppered by arguments and a lack of respect for one another, then it could be time to let go. Honour yourself and do what is best for you both. Alternatively, you might face a tough choice with significant consequences. Instead of making a decision based on your values, you feel tempted to cut corners and avoid responsibility for your actions. You may think you can get away with it, but the reversed Lovers implores you to think again and do the right thing – no matter how hard it might be.', 'lovers-reversed'),
    new card('The Chariot Reversed', 'You are at the mercy of the opposing forces and the obstacles, and cannot seem to muster the strength to take over. You are taking everything lying down, and life is dragging in any direction that it pleases. This is a wakeup call and reminder that you will need to tighten some loose ends and take charge of your destiny', 'chariot-reversed'),
    new card('Strength Reversed', 'You are (or about to) experience an intense anger or fear in your life. You seem to be lacking the inner strength that this card normally represents, meaning you might be experiencing fear, and a lack of conviction and confidence in your own abilities. You must learn to gain confidence in order to re-harness your inner strength', 'strength-reversed'),
    new card('The Hermit Reversed', 'You are perhaps in a situation where you would like to be alone; there is nothing wrong about that. However, there is a possibility that your seclusion may become harmful to both yourself and others. Though the Hermit sets forwards with noble intentions to search for his inner truth, his path inward may also be filled with great danger. Going inward may lead to madness and the abyss, for the unconscious is filled with images that he may not yet understand, lurking and waiting to lure you ever inside. You must learn to balance your need for truth with connection to your fellow human', 'hermit-reversed'),
    new card('The Wheel of Fortune Reversed', 'Luck has not been on your side and misfortunes have been following you. You must understand that thereare things that cannot be moved by human will and action alone. When we do not let go, it can bring only more suffering, for you may blame yourself for actions that could not have altered the situation. When we learn to accept, we also learn to forgive ourselves. We learn to move on, and move forward - and eventually, we learn that this feeling of acceptance can push the wheel again forward, and move it towards a new cycle.', 'wheel-reversed'),
    new card('Justice Reversed', 'The appearance of this card in reversed is to show you are living in denial. You are not willing to accept the consequences of your actions or others. You are running from your guilt. You must however, be aware that these are actions that are in the past. Your future depends on your actions today - and what you will do to tip the scales in balance again. How can you make up for your wrongs? Taking action gives you a chance to change and stop judging yourself.', 'justice-reversed'),
    new card('Hanged Man Reversed', 'The reversal meaning of the Hanged Man card represents a very specific period of time during which you feel as if you are sacrificing a significant amount of time while getting nothing in return. Do not be shy to set boundaries with yourself and others', 'hangedman-reversed'),
    new card('Death Reversed', 'The Death reversal meaning is still about change, but that you have been resisting it. You could be worried about letting go of the past, or you could not be sure of the changes that you need to make to go forward. This will limit your future, which can cause you to feel like you are in limbo. You should take some time to assess the ways that you have been approaching changes in your life. You may find you have been halting the changes that you need due to fears of the unknown. While you can still be afraid, you should trust that you are taking the right steps and move forward. Life moves on, so fighting passing time is only going to leave you with regrets.', 'death-reversed'),
    new card('Temperance Reversed', 'Temperance in reversed is a reflection of something that is out of balance and may be causing stress and anxiety. Lack of a long-term plan or vision may also be the Temperance reversal meaning. This creates a lack of purpose for you, leaving you feeling lopsided as you search here and there for what you should be doing. You must reflect and think carefully about what needs to change. Temperance reminds us that all things are only good in moderation, and that we must examine in which aspects of our lives we are breaking the balance.','temperance-reversed'),
    new card('The Devil Reversed', 'You are on the verge of a break-through or an up-levelling. However, for this to happen, you are called to confront your inner fears and anxieties to free yourself from the chains that bind you to your limiting beliefs and unhealthy attachments.', 'devil-reversed'),
    new card('The Tower Reversed', 'When you get the Tower card reversed, you can feel some crisis looming along the horizon, and you are struggling as much as you can to try and avoid its manifestation. What you have not realized is that these breakdowns can be beneficial in breaking down your reliance on something that is false. The tower is built on faulty foundations, and it must fall. Though the destruction will be painful, the humbleness resulting from it can bring us peace.', 'tower-reversed'),
    new card('The Star Reversed', 'When the Star card is reversed, it means that you are feeling as though everything has turned against you. The challenges that you would normally see as exciting seem instead to make you feel as though you cannot overcome them. You have lost faith in something, whether inside yourself or with something you normally find dear. Without hope, without faith, we cannot find the motivation to progress forward in the challenges that we face. Where in your life are you feeling hopeless? In what ways do you already feel defeated? And how does that affect your actions? The star reversed asks us to nurture our sense of hope and positive energy to help propel our actions with joy instead of fear.', 'star-reversed'),
    new card('The Moon Reversed', 'A Moon reversal in a reading can sometimes indicate that the darker and more negative aspects of the moon are present in your life. It could represent confusion and unhappiness - you want to make progress, but you are not sure what is the right thing to do. You must deal with your anxiety and fears by overcoming them, for they are like shadows in the dark. It is time to believe in yourself and move forward. Another reversed moon meaning is that the forces of the night that are bringing you confusion are starting to dissipate. You have started managing your fears and anxiety. Whatever negative energies you have been facing are slowly fading away. It presents a liberating experience as you discover the positive side of things.', 'moon-reversed'),
    new card('The Sun Reversed', 'In the reversed position, the Sun indicates that you might have significant difficulties finding positive aspects to certain situations. The clouds might be blocking out the warmth and light that you need to progress. This might be preventing you from feeling confident and powerful. You may experience certain setbacks which are damaging your optimism and enthusiasm. On the other hand, the Sun reversed might be indicative that you are being unrealistic. It might be a sign that you have an overly optimistic perception of certain situations. These are things that you need to take into account in order to ensure that you are on the right track and your successes continue as they do.', 'sun-reversed'),
    new card('Judgment Reversed', 'The reversed Judgement card can mean that you doubt and judge yourself too harshly, which could be causing you to miss opportunities that were awaiting you. The lost momentum causes you to fall behind in your plans, which can make it difficult to move forward. This means you should be moving forward with pride and confidence, not with caution. Alternatively, the card can be a push to take time out of your busy routine to reflect upon your life to this point, and what you have learned so far. You are most likely not giving yourself the time or space to fully think about the matter and learn the lessons you need to to be able to progress with awareness. You could also be too critical of your past actions, so you are not giving yourself the forgiveness to move forward. The mistakes that we have made in the past are learning tools, so they help us move though life. Focusing too hard on these mistakes can cause us to trip and fall.', 'judgment-reversed'),
    new card('The World Reversed', 'You are drawing near to something that marks the end of a journey or an era. You may have many accomplishments that have lined your path, but there is a strange emptiness that fills you when you look backwards upon it, as if you have all the pieces but they are not coming together. What is missing? Do you feel connected to what you are doing? Do you feel connected to others? What alienates you from feeling complete? From feeling whole?', 'world-reversed'),

    // suit of cups upright
    new card('Ace of Cups', 'Getting the Ace of Cups upright shows that it is time to let loose of whatever emotional baggage you have and start living your life to the fullest. Like with all the other aces, there is a new beginning that is indicated here - a chance to start fresh. It might come in the form of opening yourself up to the possibilities of new relationships, romantic or otherwise, that have the ability to make you emotionally fulfilled.', 'ace-cups'),
    new card('Two of Cups', 'This card indicates that any relationship is built on the union of forces, a strong connection and a balanced and equal partnership. When it comes to work, you may notice that the people around you will start to appreciate you more. There is a mutual respect here, meaning you will also be more comfortable in your workplace. If you are looking for new job opportunities, this card may be a good sign. In terms of love, the card represents commitment, a balanced relationship, and love. But this does not simply mean that you will no longer need to nurture your love to make it last. The card only signifies that true love and affection is present. In finances, the Two of Cups is associated with fairness and balance. This means that you are currently financially capable and you have the right amount of money to deal with your obligations. In relation with your health, people who are currently facing some health issues need to look for a practitioner that they will be comfortable working with and whom they can trust. In spirituality, it is a call for you to be more endearing and loving towards the others. You are receiving positive energy from the universe, and you need to share that energy.', 'two-cups'),
    new card('Three of Cups', 'The meaning behind the Three of Cups represents a period of happiness. You will be able to forget the worries of your daily life and spend quality time with family and friends. To see the Three of Cups can indicate a happy reunion with a long lost friend, relative, or loved one. It can also mean a celebration, whether it is your own or for someone who you love. Also, if you are having problems with your social life, this card can signal the end of those hardships. You will be able to resolve differences and learn how to deal with the problem.', 'three-cups'),
    new card('Four of Cups', 'You may feel as if there is no solution or way forward in your situation. Life has become stagnant, and nothing seems to make you happy or passionate. You are feeling apathetic - regardless of what happens, whether the day is good or bad, none of it matters to you. The Four of Cups commands a self-evaluation of your attitude so that you can pull yourself out of this rut. Our lives are short, and sometimes monotonous, but we must create meaning for ourselves. The solution is likely right in front of you, the hand is offering you a way out, but you release yourself out of your mental stubbornness and deploy new approach.', 'four-cups'),
    new card('Five of Cups', 'The Five of Cups symbolizes disappointment, and the feelings that come when things go differently as you expected. You are feeling unhappy that a certain situation hasn’t really turned out the way you have hoped it would. Instead of moving towards a more positive perspective, this card seems to say that you are dwelling in the past, inducing feelings of self-pity and regret.','five-cups'),
    new card('Six of Cups', 'The Six of Cups upright generally represents generosity, naïve happiness, and childhood. It can stand for you wanting to return to a happier time, whether it was when you were a child, teenager, or young adult. Many times, these memories are things of the past, which reflect the aspects of ourselves that have vanished. You may feel that remembering these times is the only way to feel happy. The Six of Cups appearing in a reading seems to indicate that while we may look upon the past with a happy eye, we must avoid living in it. Coming after the Five of Cups, this card can also suggest that you may have suffered a loss or disappointment of sorts, and you are making the journey home. You are looking to the past to find the answer to the crisis or challenge that you are facing now. You may be seeking the comfort and warmth of people that unconditionally love you, gathering strength to face the trials that are in front of you.', 'six-cups'),
    new card('Seven of Cups', 'To draw the Seven of Cups in a reading shows that you need to clearly see the shadows and visions in your imagination, not only in your dreams but also in the real world. You should be careful of wishful thinking and be alert of the choices that you make. Alternatively, the Seven of Cups is a reminder that although it is good to have dreams and wishes, it is even better to take action attaining those dreams. At one point in life, you will need to stop fantasizing and face the reality of life.', 'seven-cups'),
    new card('Eight of Cups', 'Getting the upright side of this card shows that you are dissatisfied with your life and need to experience a higher purpose in life. You may have been exploring your options, flitting about from one choice to another, tasting the wine in each cup, as a means to sort out what it is that you really want with your life. You are now experiencing a feeling of exhaustion - and are coming to a realization that you must step away from what is familiar. It is a choice, and a recognition that true happiness will not be found in what you have already created. ', 'eight-cups'),
    new card('Nine of Cups', 'After a long journey, the Nine of Cups symbolizes the finding of self-satisfaction. The emotional journey of the cups is starting to come to a close after the volatile ups and downs you faced in the earlier numbers of this suit. You have struggled to find purpose and joy after loss, you have tasted the different things that life offers, and you have left comfort in order to find greater heights. Here, you have found them, and you are indulging yourself as you celebrate this new stage of your life. This is also referred as the wish card, which means that the things that you desire for, or your most perfect dream is bound to happen.', 'nine-cups'),
    new card('Ten of Cups', 'From its joyful depiction, we can assume that the Ten of Cups embody happiness, joy, contentment and emotional satisfaction in your family, relationships, or companion/s. It represents an idyllic state of comfort, harmony, peace and love which makes you feel like you are in paradise. This is where all your dreams, wants, needs and wishes have been fulfilled, and you feel a complete sense of satisfaction. Take a moment and breathe, look around you and be thankful for all your blessings. This card signifies something that so many of us are searching for.', 'ten-cups'),
    new card('Page of Cups', 'One of the most important meanings within the Page of Cups is that you should be open to new ideas, especially ones that stem from intuitive inspiration. The card seems to state that such inspiration should be embraced, despite it being something that you may not expect. It could lead you to adventure and open many doors. If it is a calling of a creative nature, for example, one to get into music or art, there is an especially strong push from this card to go for it. For those that are afraid to reveal their emotions, the Page of Cups could mean that it is time to release and show those emotions. The creative you and the emotional you should both be expressed, no matter how insignificant they may seem. In most cases, some people cannot express themselves as they want to protect their ego. The Page of Cups indicates that it is alright to have a new beginning - to welcome the real you.', 'page-cups'),
    new card('Knight of Cups', 'When faced with an actual decision, the Knight of Cups is going to listen to their heart, regardless of whether this is actually a logical choice or not. They can also manifest as an event or a person in your life, or a part of your own self. They appears as a messenger – and with them, they carry an invitation or an arrival of something or someone which is going to have a certain emotional benefit for you. As a knight, they are also charged with taking the gifts of their suit, and bringing it outward into the world. They therefore can also represent the undertaking of some project with significant emotional or creative value for you.', 'knight-cups'),
    new card('Queen of Cups', 'The Queen of Cups is seen as compassionate, caring, sensitive, and nurturing. They connect with people on the emotional level, so people enjoy their honesty and fairness. The appearance of the Queen of Cups in a reading can be guiding you to find help from others. Most times, like the other queens, this is a feminine figure that will come into your life. Most times, the Queen of Cups can also represent the trusted inner voice you have within you. They seem to say that you should take the time to focus on your emotional health before trying to help others. Self-love creates compassion. The Queen of Cups normally thinks with their hearts, instead of their mind. They can lack rationality and common sense, but they can also be intuitive, dreamy and almost psychic at times. The Queen of Cups could be the answer to your problems when a logical approach is not working.', 'queen-cups'),
    new card('King of Cups', 'The King of Cups represents creativity, emotion, and the unconscious. The card shows the ability to restrain emotions and be fully in charge of your feelings and impulses. Therefore, the King of Cups represents a balance between the intellect and emotions. When you have balanced your emotions and are able to control them, it means that you have a deeper knowledge and awareness of yourself. When you are faced with challenges that would normally throw you off balance, the King of Cups is there to remind you that you should act as he does - do not fly out in a rage, or immediately throw yourself into despair! You first need to temper the state of your emotions, so that you can progress forward in reality. Learn to evaluate yourself so as to determine how you can create a stronger awareness of your own internal state. There are instances when the King of Cups can symbolize an older individual who is in your life. This is a mature person who is willing to take responsibility for their actions and has mastered their self-understanding.', 'king-cups'),

    //suit of cups reversed
    new card('Ace of Cups Reversed', 'Seeing the Ace of Cups upside down during your reading means you have been enduring emotional instability or pain for some time. There is a loss that is indicated here, and perhaps something that has meant much to you is no longer giving you the joy that it once had. Since the cups also govern creativity, you may also be experiencing a creative block of sorts, and where the waters of inspiration once flowed, they have now dried up.  In all these cases you must examine who or what is in control of the cup - which party allowed it to overturn? What can you do to place it right side up again?', 'ace-cups-reversed'),
    new card('Two of Cups Reversed', 'When reversed, the Two of Cups can mean that the balance that was once there is broken. This balance was an integral part of keeping the individuals together, but to break it is to create disconnection and discord. The negative energy of two forces is present, and instead of them joining or attracting, they seem to repel each other.You may be finding that certain small details that were not problems before are coming into play, signaling that one party may have resentments. A line of communication that allowed you and the other party to openly talk about disagreements has been cut off, only worsening the cycle of resentment and imbalance.Be the first to open up, and you may find the problem much easier to repair than you thought it would be.', 'two-cups-reversed'),
    new card('Three of Cups Reversed', 'When the Three of Cups is reversed, it means that you may have no time to socialize or go out with friends. You may be too busy with school or work that you can’t spare some time to have fun. The Three of Cups reversed can also mean losing touch with some of your friends. As time passes, you may find that you are growing apart from one another. When we grow older, we must put in effort to make sure that our friendships are not neglected. Alternatively, the Three of Cups reversed can mean that there is a lack of balance and harmony within your social circle. Gossip and scandal can rear their ugly heads. Perhaps there is envy hidden within this circle, and as a result, you are feeling isolated.', 'three-cups-reversed'),
    new card('Four of Cups Reversed', 'While in the upright four of cups, you may be suffering from apathy and ignore the opportunities that the universe offers you, the reversed four of cups signals the desire to have a new start. You are coming to the understanding that though life is not perfect, there is beauty in it, and joy comes from choosing to see this beauty. Embrace new ideas, new people and new places; because you never know where these adventures can take you. Many may miss these chances because they are too confined in their own beliefs and ambitions.', 'four-cups-reversed'),
    new card('Five of Cups Reversed', 'When the card is reversed, the Five of Cups shows a significant recovery from the regret as well as proper acceptance of your past. You are beginning to realize all of the implications of your actions, and you have finally come to appreciate the lessons which can be learned from that experience. You are seeing that the suffering and grief that you endured gave you strength and imbued you with resilience. You are ready to pick up the two remaining cups which are still full and go on with your life in full force.','five-cups-reversed'),
    new card('Six of Cups Reversed', 'The Six of Cups reversed can mean that you are clinging to the past. You should explore your memories, but you should not allow yourself to remain there. While you may find it comforting to be in the security of home, you must also learn to forge your own path. The past should be used as a guide for the future. Learn to focus on the present, and truly be aware. Another reading of the Six of Cups reversed is that you may feel as though you are disconnected from your childhood self and dreams, which may sometimes be unrealistic. Not reaching these goals can be painful, but sometimes reality carves a path for you that you must follow, and you should not blame yourself for your choices. Take the time to think about where you want to be now and how you can reach your goals, instead of just dreaming about them.', 'six-cups-reversed'),
    new card('Seven of Cups Reversed', 'The Seven of Cups reversal is somewhat similar to the upright, as they both indicate dreams, illusions and temptations, but seem to emphasize the more negative qualities of this card. Your views may be inclined towards fantasy, and not grounded in reality. It may imply that you are unclear about the things that you are searching for. The Seven of Cups reversed may also demonstrates your unwillingness to face the realities of life, and you are seeking to escape through imagination and daydreaming. On the other hand, the Seven of Cups reversed may also indicate an end of confusion, of cutting out illusions, and moving forward with clarity.', 'seven-cups-reversed'),
    new card('Eight of Cups Reversed', 'Getting the reversed Eight of Cups can show that one is in a state of confusion about which path they are supposed to take. The confusion usually arises from not knowing what is best for you and in the end, drifting in a sea of uncertainty is going to be the resulting effect. On the other hand, you may be aware of what you need to do. There is something that in your life that has for a long time stopped bringing you joy or pleasure, and though the desire of your soul is to fly away from it, you find yourself remaining. The thought of leaving the security of what you have built fills you with fear - you are scared of both change and of losing something that has given you great comfort. You must have courage, believe that you deserve better, and that there are even more joyous things that are awaiting you if you take this journey. ', 'eight-cups-reversed'),
    new card('Nine of Cups Reversed', 'When the Nine of Cups is reversed, you need to think more carefully about the things that you really want in your life. The Nine of Cups reversed can signify that you are looking for a more authentic feeling of fulfillment. Your path has been a hard one, and you have arrived at a period where you may have the appearance of fulfillment, but something else is missing. This may outwardly appear as smugness, and can indicate your desire to receive attention and recognition for all that you have achieved. But you personally still feel dissatisfaction in yourself - it seems as though your desires are never-ending, a black hole. Where does this stem from? In what parts of yourself are you lacking confidence?', 'nine-cups-reversed'),
    new card('Ten of Cups Reversed', 'When the Ten of Cups is reversed, the strong bonds that one forges with family and community are broken, or twisted. The Ten of Cups is truly the happily ever after card, but somehow this idealized image of domestic peace and comfort is broken, or was unrealistic all along. Instead of connections, you may find distance. Instead of coming together, you may be pulling apart. Your hopes for happy times and special moments seem to not meet your expectations. You should learn to treat each other well, love each other and care for each other. This is the best way to ensure that you retain your harmonious living.', 'ten-cups-reversed'),
    new card('Page of Cups Reversed', 'You are undergoing a block in your creativity. There are things/projects that you find interesting, but you seem to do them for other reasons than for the joy of it. You may be doing them for money, for fame, or something else. Remember the joy that your projects brought you in the first place to reclaim your imaginative spirit. The Page of Cups could indicate that someone (either you or someone around you) lacks inspiration. They are battling low self-worth, and they are afraid of reality whether it is emotional, financial, health-related, etc. Think about what can you do to help inspire yourself/them to be your/their best self?', 'page-cups-reversed'),
    new card('Knight of Cups Reversed', 'Reversed, the Knight of Cups means that you allow your emotions to control your life a lot more than you should. You might be overly jealous, emotional or moody. In fact, this could get up to the point of actual incapacity to take action, which is most definitely to be avoided. Jumping to conclusions too fast is characteristic of a reversed Knight of Cups, and making judgements without having the necessary information is very common. The card indicates a situation which could be considered appealing at first but quickly turns out to be something very different. With such high expectations, everyone will walk away quite disappointed.', 'knight-cups-reversed'),
    new card('Queen of Cups Reversed', 'The Queen of Cups reversed means that you are not in sync with your emotions. You can also feel restricted in the expressing the way that you truly feel. Most times, bottling up your emotions can be very damaging and will lead to a boiling point in the near future. You may have high levels of stress that you are not able to cope with anymore. The Queen of Cups reversed can also reflect that your mind is wandering too far, and you are letting your imagination run away with itself. While you still mean well, you should take a pause to really see whether your emotions can be trusted, because you are allowing them to control you.', 'queen-cups-reversed'),
    new card('King of Cups Reversed', 'The King of Cups reversed signals what happens when they are at their worst: volatility, emotional manipulation and moodiness. When the King of Cups falters, their usual ability to handle situations with compassion and wisdom are turned upside down. They are unable to balance the needs of all that seek his guidance, and while appearing kind to some, may be cold to others. Their talent in navigating the emotions of others may be put to dubious uses, manipulating circumstances to fit their needs. The reversed King of Cups suggests that there is a character in your life that is depicted by this card, whether a part of you or someone else.', 'king-cups-reversed'),

    //suit of wands upright
    new card('Ace of Wands', 'When you draw the Ace of Wands, it is an indicator that you should just go for it. Take the chance and pursue an idea that you have in mind. Take the first steps to start the creative project. The Ace of Wands calls out to you to follow your instincts. If you think that the project that you have been dreaming of is a good idea, and then just go ahead and do it. ', 'ace-wands'),
    new card('Two of Wands', 'The Two of Wands is a more mature version of the ace of wands, meaning that that this tarot card is all about planning and moving forward – progression. Look at it this way; you have already set out to achieve a particular task, which means you have turned an idea into a realistic plan. Such a plan will require fulfillment and therefore you have to progress from just having the plan to actually achieving what you set out for.', 'two-wands'),
    new card('Three of Wands', 'The symbolism within the Three of Wands is that opportunities can to widen your horizons in many areas. It also is a warning to keep your mind open as better opportunities could open up to you. As you take steps towards achieving what you set out to do, you are also becoming more aware of opportunities that are coming your way, and this could be take you out of your comfort zone. This pushes you to sometimes embrace change, and to start thinking in the long-term.', 'three-wands'),
    new card('Four of Wands', 'The Four of Wands poses that this is the perfect time for you to get together with close people such as friends and family. This could be with or without any special occasion. Oftentimes the card is known to reflect a period of holidays when you are together with your friends and family for an extended period of time. It might also be suggesting for you to invite your closest friends for a great and intimate dinner and share a laugh or two.', 'four-wands'),
    new card('Five of Wands', 'Five of Wands suggests that there is form of conflict in one’s life. This may be an existing conflict or one that is brewing and may eventually blow up. It may also depict a problem in communication, for example in a situation where no one really wants to listen to the other - meaning that no agreement or understanding takes place. The five men may signify problems in a group of people who are not patient enough to listen to what anyone else is saying. They only want to be heard, and since none of the others will listen, they all argue at once. Much of this can be solved by the querent taking the first step to try and initiate communication in such a way that you suggest that everyone airs out what they have to say, one at a time. By doing this, you will be able to address the problem, and everyone will be heard. ','five-wands'),
    new card('Six of Wands', 'The card is indicative that you have managed to harness the strengths and talents that you have within you in an attempt to bring a particularly successful outcome in your life. You have managed to properly get through the confusion which is brought by the card before this one – the Five of Wands, and managed to properly minimize distractions, thus successfully focusing on your goals and achieving them. It’s also worth noting that there is a slight downside apart from the overall positivity that stems from the card. It can bring self-importance as well as egotistical behavior and arrogance. This could make you think that nobody is better than you.', 'six-wands'),
    new card('Seven of Wands', 'The Seven of Wands however is different as it is is about the struggle that you need to go through to maintain your position, rather than to attain it. This is about the difficulties we face to continue to have success. You should be ready for the competition to you defend your title, and to prove yourself. Others are going to desire the same results that you do, so you need to stay ahead of the them. There will be challenges to the success of your project or venture from an outside source. You must remain dedicated to your desires, and with a clear purpose and effort, you will overcome them.', 'seven-wands'),
    new card('Eight of Wands', 'Difficulties that were brought by the Seven of Wands are finally over. It signifies a strong level of energy which states that different aspects of your life will be trailblazing. Perhaps important news will be coming on your way, and you may experience a sudden, yet steady positive growth.', 'eight-wands'),
    new card('Nine of Wands', 'The Nine of Wands tarot card is one that symbolizes great hope even when one is faced by many problems that threaten to make them lose their balance. The Nine of Wands symbolizes a life which has undergone too many trials but through their determination and will, they were able to overcome them.', 'nine-wands'),
    new card('Ten of Wands', 'This card shows that you have already completed the circle of struggle. After spending too many resources and lots of energy looking for success, you have finally overcome the obstacles. The sweat off your brow was worth it - your efforts have finally been rewarded. You may find yourself living in a world of abundance where poverty and suffering have no chance to intervene.', 'ten-wands'),
    new card('Page of Wands', 'When you get the Page of Wands, it simply means something is within you, something that triggers you to make discoveries, indulge in investments or take the next advancement in life. You could be just about to take a move on a certain idea, but some conflicting messages keep coming to your mind, and you get discouraged. This card resembles your inner battles which are preventing you from expressing your heroism to the world, to let the world know that you exist for a reason.', 'page-wands'),
    new card('Knight of Wands', 'When this card appears, it means a great time to get away and travel. The person should feel charged up and ready to get things done. He is adventurous and can find fun things to do no matter where they are. There is never a dull moment when the Knight of Wands is around. If you are starting a creative project, then you should do so with lots of energy and enthusiasm. However, you should balance it with realistic and well-rounded views. You should also have a plan that takes into account the consequences of your actions.', 'knight-wands'),
    new card('Queen of Wands', '', 'queen-wands'),
    new card('King of Wands', '', 'king-wands'),

    //suit of wands reversed
    new card('Ace of Wands Reversed', 'The reversed Ace of Wands indicates trials and tribulations that you will face in the near future. You might not have any direction, which leads to being uninspired or unmotivated. At this point of your life, you might not know what you really want to do. You don’t know how to get out of the slump. In the case that you already have a goal, you are not excited to achieve it. When you draw a reversed Ace of Wands, you should consider taking some time off to allow inspiration to come to you. You feel weighed down by your current commitments and responsibilities that you can’t come up with new ideas, or muster the passion to push forward in your projects.', 'ace-wands-reversed'),
    new card('Two of Wands Reversed', 'The Two of Wands reversed meaning suggests the need to set up long-term goals. Begin the process of setting up your goals by identifying what to you is important. Proceed by planning how you intend on achieving such goals.', 'two-wands-reversed'),
    new card('Three of Wands Reversed', 'Three of Wands reversed meaning is a nudge to include planning for future changes, and to watch for better options in case that they show up. The figure on the Three of Wands knows this and always keeps his eyes open for how the future could change, and it is a worthy lesson to learn.', 'three-wands-reversed'),
    new card('Four of Wands Reversed', 'The reversal position of Four of Wands implies that there is a breakdown or complete lack of harmony in your family or in your home. It’s highly likely that there is a lot of tension between the members of your family or other loved ones. If you have completed something that is important to you, you are expecting to share it with those that are closest to you, and to come home to a welcome celebration, but instead, you find a lack of support. This may leave you feeling rather uncertain when it comes to your own relationships as well as the things that you can and cannot depend on.', 'four-wands-reversed'),
    new card('Five of Wands Reversed', 'The Five of Wands reversed meaning can be that your natural method of dealing with disagreements is avoiding any kind of conflict by getting away from that place as fast as you can. Sometimes this can be regarded as a good thing, but other times, it may lead to a number of issues that are brewing up within you, for which you will have to address soon. On the other hand, it can also mean that you have worked through your troubles and that you do not have any more issues to worry about.','five-wands-reversed'),
    new card('Six of Wands Reversed', 'When the card is reversed, this suggests that you might find yourself doubting all of your abilities as well as your overall potential to achieve any kind of success. You might be feeling particularly negative about your entire self as if you have failed others as well as yourself. You need the overall support as well as recognition of third parties in order to pick you up, to emotionally provide you with some much-needed strength.', 'six-wands-reversed'),
    new card('Seven of Wands Reversed', 'The Seven of Wands reversal means that you could be feeling overwhelmed by all the responsibilities and challenges that you are facing. This can make it difficult to see the whole picture. You can also feel that you have to compete and compare yourself to other people, which leaves you feeling vulnerable and inadequate. Avoiding conflict and backing down is also common with the reversed Seven of Wands. This can lead to unhappiness because you run away from activities and relinquish your goals, when you are challenged by anyone. Remember all that you fought for to be here, and think carefully on whether you truly believe that is worth giving up now. Another reading of the Seven of Wands reversed can also be that you are being too aggressive when you are protecting yourself and damaging your relationships by doing so.', 'seven-wands-reversed'),
    new card('Eight of Wands Reversed', 'Eight of Wands reversed  is generally associated with patience. There is a possibility that you are feeling frustrated about something. You might now see that what you set in motion earlier created the obstacles that you are discovering right now. It is time for you to understand that you cannot change the past. You must forgive yourself, and adapt your strategy.', 'eight-wands-reversed'),
    new card('Nine of Wands Reversed', 'The Nine of Wands reversed shows a person who may not be a risk taker; they may not want to make a long-term move or commitment since they are afraid that they may not be able to come out of it. They are mistrustful and hence have created a boundary between themselves and others which is turning to be their own personal prison. You may be afraid that you do not have enough resources to face some upcoming challenges, which is why you may be open to running away or avoiding it.', 'nine-wands-reversed'),
    new card('Ten of Wands Reversed', 'When the Ten of Wands card is reversed, it indicates that you are truly burdened by circumstances which are not necessary in your life. Look around and see what is bothering you that will not positively impact yourself even if you rectify it. Drop them all. Anything that does not add value in your life is not worth your time, so let it go.', 'ten-wands-reversed'),
    new card('Page of Wands Reversed', 'With the Page of Wands reversed, it tends to emphasize the more negative character traits of the upright version. They tend to show up when your mind is filled with one great idea after another, and are unable to progress beyond the beginning planning stages. Perhaps you have started a project or a hobby expecting that it would grow to great levels and instead you end up nowhere. As painful as it is, it is a good way of telling you that you should venture into other meaningful projects and avoid wasting time.', 'page-wands-reversed'),
    new card('Knight of Wands Reversed', 'When you get a reversed Knight of Wands, it indicates frustrations and delays. You may feel angry and that you are not getting anywhere. A reversed Knight of Wands can translate to a loss of power. You may be trying to compensate for something that you don’t have total control over - this might lead to pessimism and loss of self-esteem.', 'knight-wands-reversed'),
    new card('Queen of Wands Reversed', 'There is a probability that you will encounter obstacles that will hamper your progress. Do not mind these obstacles and continue doing your job as you see fit. To see this card may also be a reminder to adhere to your rational side - to balance your sometimes chaotic energy with clear though, and you will be more successful.', 'queen-wands-reversed'),
    new card('King of Wands Reversed', '', 'king-wands-reversed'),

    //suit of swords upright
      new card('Ace of Swords', '', 'ace-swords'),
      new card('Two of Swords', '', 'two-swords'),
      new card('Three of Swords', '', 'three-swords'),
      new card('Four of Swords', '', 'four-swords'),
      new card('Five of Swords', '','five-swords'),
      new card('Six of Swords', '', 'six-swords'),
      new card('Seven of Swords', '', 'seven-swords'),
      new card('Eight of Swords', '', 'eight-swords'),
      new card('Nine of Swords', '', 'nine-swords'),
      new card('Ten of Swords', '', 'ten-swords'),
      new card('Page of Swords', '', 'page-swords'),
      new card('Knight of Swords', '', 'knight-swords'),
      new card('Queen of Swords', '', 'queen-swords'),
      new card('King of Swords', '', 'king-swords'),
    
    //suit of swords reversed
    new card('Ace of Swords Reversed', '', 'ace-swords-reversed'),
    new card('Two of Swords Reversed', '', 'two-swords-reversed'),
    new card('Three of Swords Reversed', '', 'three-swords-reversed'),
    new card('Four of Swords Reversed', '', 'four-swords-reversed'),
    new card('Five of Swords Reversed', '','five-swords-reversed'),
    new card('Six of Swords Reversed', '', 'six-swords-reversed'),
    new card('Seven of Swords Reversed', '', 'seven-swords-reversed'),
    new card('Eight of Swords Reversed', '', 'eight-swords-reversed'),
    new card('Nine of Swords Reversed', '', 'nine-swords-reversed'),
    new card('Ten of Swords Reversed', '', 'ten-swords-reversed'),
    new card('Page of Swords Reversed', '', 'page-swords-reversed'),
    new card('Knight of Swords Reversed', '', 'knight-swords-reversed'),
    new card('Queen of Swords Reversed', '', 'queen-swords-reversed'),
    new card('King of Swords Reversed', '', 'king-swords-reversed'),

    //suit of pentacles upright
    new card('Ace of Pentacles', '', 'ace-pentacles'),
    new card('Two of Pentacles', '', 'two-pentacles'),
    new card('Three of Pentacles', '', 'three-pentacles'),
    new card('Four of Pentacles', '', 'four-pentacles'),
    new card('Five of Pentacles', '','five-pentacles'),
    new card('Six of Pentacles', '', 'six-pentacles'),
    new card('Seven of Pentacles', '', 'seven-pentacles'),
    new card('Eight of Pentacles', '', 'eight-pentacles'),
    new card('Nine of Pentacles', '', 'nine-pentacles'),
    new card('Ten of Pentacles', '', 'ten-pentacles'),
    new card('Page of Pentacles', '', 'page-pentacles'),
    new card('Knight of Pentacles', '', 'knight-pentacles'),
    new card('Queen of Pentacles', '', 'queen-pentacles'),
    new card('King of Pentacles', '', 'king-pentacles'),
    
    // suit of pentacles reversed
    new card('Ace of Pentacles Reversed', '', 'ace-pentacles-reversed'),
    new card('Two of Pentacles Reversed', '', 'two-pentacles-reversed'),
    new card('Three of Pentacles Reversed', '', 'three-pentacles-reversed'),
    new card('Four of Pentacles Reversed', '', 'four-pentacles-reversed'),
    new card('Five of Pentacles Reversed', '','five-pentacles-reversed'),
    new card('Six of Pentacles Reversed', '', 'six-pentacles-reversed'),
    new card('Seven of Pentacles Reversed', '', 'seven-pentacles-reversed'),
    new card('Eight of Pentacles Reversed', '', 'eight-pentacles-reversed'),
    new card('Nine of Pentacles Reversed', '', 'nine-pentacles-reversed'),
    new card('Ten of Pentacles Reversed', '', 'ten-pentacles-reversed'),
    new card('Page of Pentacles Reversed', '', 'page-pentacles-reversed'),
    new card('Knight of Pentacles Reversed', '', 'knight-pentacles-reversed'),
    new card('Queen of Pentacles Reversed', '', 'queen-pentacles-reversed'),
    new card('King of Pentacles Reversed', '', 'king-pentacles-reversed'),
  ];
  
  function getRandom(num){
    var randomNumber = Math.floor(Math.random() * num);
    return randomNumber;
  }
  
  document.getElementById("draw").onclick = function(){
    var index = getRandom(156);
    var currentCard = deck[index];
  
    document.getElementById("display").innerHTML = '<img src="images/' + currentCard.image + '.jpg"><h3>' + currentCard.name + '</h3><p>' + currentCard.description + '</p>';
  };
